// =============================================================
//  YOUR COLLECTION
// -------------------------------------------------------------
//  This is your data file. To add a quote, copy one line below,
//  paste it, and change the words between the quotes.
//
//  Each entry needs:
//    text:   the quote itself
//    source: who said it (or where it's from)
//
//  Keep the curly braces { } and the comma at the end of each
//  line. That's it — save the file and refresh the browser.
// =============================================================

// NOTE: Order is arranged so the daily quote is non-Icelandic for ~13 months
// (from 2026-05-25), after which Icelandic quotes begin.
// Adding/removing quotes will shift this — re-run the reorder if you need it again.
const QUOTES = [
  { text: "The first Velvet Underground album only sold 10,000 copies, but everyone who bought it formed a band.", source: "Brian Eno" },
  { text: "Lesser artists borrow; great artists steal.", source: "Igor Stravinsky" },
  { text: "To play a wrong note is insignificant; to play without passion is inexcusable.", source: "Ludwig van Beethoven" },
  { text: "The shorter way to do many things is to only do one thing at a time.", source: "Wolfgang Amadeus Mozart" },
  { text: "I play the notes as they are written, but it is God who makes the music.", source: "Johann Sebastian Bach" },
  { text: "Music is the silence between the notes.", source: "Claude Debussy" },
  { text: "I have nothing to say and I am saying it and that is poetry.", source: "John Cage" },
  { text: "Music is a place where you can lose yourself and find yourself at the same time.", source: "Philip Glass" },
  { text: "An artist's duty, as far as I'm concerned, is to reflect the times.", source: "Nina Simone" },
  { text: "The blues was like that problem child that you may have had in the family. You was a little bit ashamed to let anybody see him, but you loved him.", source: "B.B. King" },
  { text: "One chord is fine. Two chords is pushing it. Three chords and you're into jazz.", source: "Lou Reed" },
  { text: "I'm not ashamed to dress 'like a woman' because I don't think it's shameful to be a woman.", source: "Iggy Pop" },
  { text: "The best revenge is massive success.", source: "Frank Sinatra" },
  { text: "It isn't where you came from. It's where you're going that counts.", source: "Ella Fitzgerald" },
  { text: "If I'm going to sing like someone else, then I don't need to sing at all.", source: "Billie Holiday" },
  { text: "Music is the strongest form of magic.", source: "Marilyn Manson" },
  { text: "Talent is a long patience, and originality an effort of will and intense observation.", source: "Gustave Flaubert" },
  { text: "Without music, life would be a mistake.", source: "Friedrich Nietzsche" },
  { text: "Music produces a kind of pleasure which human nature cannot do without.", source: "Confucius" },
  { text: "Music expresses that which cannot be said and on which it is impossible to be silent.", source: "Victor Hugo" },
  { text: "Where words fail, music speaks.", source: "Hans Christian Andersen" },
  { text: "Music is the literature of the heart; it commences where speech ends.", source: "Alphonse de Lamartine" },
  { text: "After silence, that which comes nearest to expressing the inexpressible is music.", source: "Aldous Huxley" },
  { text: "I would rather write 10,000 notes than a single letter of the alphabet.", source: "Ludwig van Beethoven" },
  { text: "Hell is full of musical amateurs.", source: "George Bernard Shaw" },
  { text: "The only truth is music.", source: "Jack Kerouac" },
  { text: "My music is best understood by children and animals.", source: "Igor Stravinsky" },
  { text: "Pop music is the classical music of now.", source: "Paul McCartney" },
  { text: "When the going gets weird, the weird turn pro.", source: "Hunter S. Thompson" },
  { text: "Find what you love and let it kill you.", source: "Charles Bukowski" },
  { text: "Your body is not a temple, it's an amusement park. Enjoy the ride.", source: "Anthony Bourdain" },
  { text: "What can be asserted without evidence can also be dismissed without evidence.", source: "Christopher Hitchens" },
  { text: "Inside every cynical person, there is a disappointed idealist.", source: "George Carlin" },
  { text: "It's only after we've lost everything that we're free to do anything.", source: "Chuck Palahniuk" },
  { text: "Democracy is the theory that the common people know what they want, and deserve to get it good and hard.", source: "H.L. Mencken" },
  { text: "Between two evils, I always pick the one I never tried before.", source: "Mae West" },
  { text: "It is dangerous to be right when the government is wrong.", source: "Voltaire" },
  { text: "I would never die for my beliefs because I might be wrong.", source: "Bertrand Russell" },
  { text: "The trouble with the world is that the stupid are cocksure and the intelligent are full of doubt.", source: "Bertrand Russell" },
  { text: "I've been things and seen places.", source: "Mae West" },
  { text: "Hell is other people.", source: "Jean-Paul Sartre" },
  { text: "If you're going through hell, keep going.", source: "Winston Churchill" },
  { text: "The mass of men lead lives of quiet desperation.", source: "Henry David Thoreau" },
  { text: "I'm not afraid of death; I just don't want to be there when it happens.", source: "Woody Allen" },
  { text: "We're all going to die, all of us — what a circus! That alone should make us love each other, but it doesn't.", source: "Charles Bukowski" },
  { text: "The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man.", source: "George Bernard Shaw" },
  { text: "Time is the only true measure of any man.", source: "Halldór Laxness" },
  { text: "When the wind blows, some build walls; others build windmills.", source: "Vigdís Finnbogadóttir" },
  { text: "Margur verður af aurum api.", source: "Óþekktur" },
  { text: "Ekki er allt gull sem glóir.", source: "Óþekktur" },
  { text: "Betra er seint en aldrei.", source: "Óþekktur" },
  { text: "Margt smátt gerir eitt stórt.", source: "Óþekktur" },
  { text: "Sjaldan er ein báran stök.", source: "Óþekktur" },
  { text: "Oft er í koti kátt.", source: "Óþekktur" },
  { text: "Enginn veit sína ævina fyrr en öll er.", source: "Óþekktur" },
  { text: "Maður er manns gaman.", source: "Óþekktur" },
  { text: "Margur heldur mig sig.", source: "Óþekktur" },
  { text: "Verkin tala.", source: "Óþekktur" },
  { text: "Enginn er fullnuma.", source: "Óþekktur" },
  { text: "Það er ekki sopið kálið þótt í ausuna sé komið.", source: "Óþekktur" },
  { text: "Sjón er sögu ríkari.", source: "Óþekktur" },
  { text: "Betri er einn fugl í hendi en tveir í skógi.", source: "Óþekktur" },
  { text: "Morgunstund gefur gull í mund.", source: "Óþekktur" },
  { text: "Oft verður flagð undir fögru skinni.", source: "Óþekktur" },
  { text: "Kapp er best með forsjá.", source: "Óþekktur" },
  { text: "Margur er knár þótt hann sé smár.", source: "Óþekktur" },
  { text: "Enginn verður óbarinn biskup.", source: "Óþekktur" },
  { text: "Dramb er falli næst.", source: "Óþekktur" },
  { text: "Sá er vinur sem í raun reynist.", source: "Óþekktur" },
  { text: "Margur er af aurum api og af auraleysi api.", source: "Óþekktur" },
  { text: "Það sem ekki drepur mann herðir mann.", source: "Óþekktur" },
  { text: "Frestað verk er oftast verr unnið.", source: "Óþekktur" },
  { text: "Mikill er máttur vanans.", source: "Óþekktur" },
  { text: "Ekki er ráð nema í tíma sé tekið.", source: "Óþekktur" },
  { text: "Lengi býr að fyrstu gerð.", source: "Óþekktur" },
  { text: "Margur er gildur þótt hann sé ekki langur.", source: "Óþekktur" },
  { text: "Þar sem hjartað er, þar er heimilið.", source: "Óþekktur" },
  { text: "Margur þykist meira en hann er.", source: "Óþekktur" },
  { text: "Ekki er allt sem sýnist.", source: "Óþekktur" },
  { text: "Oft reynist lítið lán stórum feng.", source: "Óþekktur" },
  { text: "Það er betra að gefa en þiggja.", source: "Óþekktur" },
  { text: "Mál er að mæla.", source: "Óþekktur" },
  { text: "Eigi fellur tré við fyrsta högg.", source: "Óþekktur" },
  { text: "Maður uppsker eins og hann sáir.", source: "Óþekktur" },
  { text: "Lítill neisti kveikir stóran eld.", source: "Óþekktur" },
  { text: "Allt er vænt sem vel er grænt.", source: "Óþekktur" },
  { text: "Það eru margir um hituna.", source: "Óþekktur" },
  { text: "Margur verður af litlu glaður.", source: "Óþekktur" },
  { text: "Enginn er eyland.", source: "Óþekktur" },
  { text: "Það er mannlegt að skjátlast.", source: "Óþekktur" },
  { text: "Betra er að bíta í skjaldarrendur en bugast.", source: "Óþekktur" },
  { text: "Oft er þörf en nú er nauðsyn.", source: "Óþekktur" },
  { text: "Sá hlær best sem síðast hlær.", source: "Óþekktur" },
  { text: "Enginn verður ólærður af lestri.", source: "Óþekktur" },
  { text: "Margur sér ofsjónum yfir annarra gæðum.", source: "Óþekktur" },
  { text: "Ekki er til sá hlutur sem öllum líkar.", source: "Óþekktur" },
  { text: "Snemma beygist krókurinn.", source: "Óþekktur" },
  { text: "Maður verður að bera sinn kross.", source: "Óþekktur" },
  { text: "Vinur er sá sem til vamms segir.", source: "Óþekktur" },
  { text: "Þar liggur hundurinn grafinn.", source: "Óþekktur" },
  { text: "Margur leitar langt yfir skammt.", source: "Óþekktur" },
  { text: "Hver er sinnar gæfu smiður.", source: "Óþekktur" },
  { text: "Mikill er sá sem sjálfan sig sigrar.", source: "Óþekktur" },
  { text: "Enginn getur allt.", source: "Óþekktur" },
  { text: "Þolinmæði þrautir vinnur allar.", source: "Óþekktur" },
  { text: "Sá sem ekki reynir fær engu áorkað.", source: "Óþekktur" },
  { text: "Hægt er að fara hratt.", source: "Óþekktur" },
  { text: "Góð byrjun er hálfnað verk.", source: "Óþekktur" },
  { text: "Málmurinn reynist í eldinum.", source: "Óþekktur" },
  { text: "Reynslan er besti skólinn.", source: "Óþekktur" },
  { text: "Lifðu í sátt við sjálfan þig.", source: "Óþekktur" },
  { text: "Hver fugl syngur með sínu nefi.", source: "Óþekktur" },
  { text: "Enginn sér sína eigin bakhlið.", source: "Óþekktur" },
  { text: "Það sem vel er gert er vel gert.", source: "Óþekktur" },
  { text: "Maður lærir meðan hann lifir.", source: "Óþekktur" },
  { text: "Allir vilja liljuna en enginn rótarstarfið.", source: "Óþekktur" },
  { text: "Oft veldur lítill steinn þungu hlassi.", source: "Óþekktur" },
  { text: "Hollur er heimafenginn baggi.", source: "Óþekktur" },
  { text: "Betri er berfættur en bóklaus.", source: "Óþekktur" },
  { text: "Mikil er gæfa góðrar samvisku.", source: "Óþekktur" },
  { text: "Enginn er verri þótt hann vökni.", source: "Óþekktur" },
  { text: "Sá sem sefur syndar ekki.", source: "Óþekktur" },
  { text: "Lengi man sá sem fær.", source: "Óþekktur" },
  { text: "Hver verður að taka ábyrgð á sínu.", source: "Óþekktur" },
  { text: "Málmur klingir mest sem er tómur.", source: "Óþekktur" },
  { text: "Þeir sem róa tveimur árum fara í hring.", source: "Óþekktur" },
  { text: "Enginn verður spámaður í sínu föðurlandi.", source: "Óþekktur" },
  { text: "Margt má bæta með góðu móti.", source: "Óþekktur" },
  { text: "Víst er að enginn sleppur við sjálfan sig.", source: "Óþekktur" },
  { text: "Þar sem vilji er, þar er vegur.", source: "Óþekktur" },
  { text: "Sannleikurinn er sagna bestur.", source: "Óþekktur" },
  { text: "Maður á ekki að kasta steinum úr glerhúsi.", source: "Óþekktur" },
  { text: "Það er hægara sagt en gert.", source: "Óþekktur" },
  { text: "Ekki skal daginn lofa fyrr en að kvöldi.", source: "Óþekktur" },
  { text: "Sá sem áttar sig ekki á mistökum sínum endurtekur þau.", source: "Óþekktur" },
  { text: "Það sem fæst auðveldlega er sjaldan mikils metið.", source: "Óþekktur" },
  { text: "Margur er blindur á eigin bresti.", source: "Óþekktur" },
  { text: "Best er að vera viðbúinn.", source: "Óþekktur" },
  { text: "Fáir vita fyrr en reynt er.", source: "Óþekktur" },
  { text: "Holl ráð eru gulls ígildi.", source: "Óþekktur" },
  { text: "Sá sem vill allt missir oft allt.", source: "Óþekktur" },
  { text: "Oft kemur gott úr því sem illt virtist.", source: "Óþekktur" },
  { text: "Góður orðstír er dýrmætur auður.", source: "Óþekktur" },
  { text: "Enginn kemst hjá því að eldast.", source: "Óþekktur" },
  { text: "Lífið er ferðalag, ekki áfangastaður.", source: "Óþekktur" },
  { text: "Sáttur hugur er besta auðæfið.", source: "Óþekktur" },
  { text: "Ekki eru allar dyggðir í andliti fólgnar.", source: "Halldór Kiljan Laxness" },
  { text: "Sá er ekki altaf tryggastur sem situr kjur, heldur hinn sem kemur aftur.", source: "Halldór Kiljan Laxness" },
  { text: "Ekkert á jörðinni er eins yndislegt og sönn ást milli pilts og stúlku í góðu veðri um nótt á voru, þegar hestarnir eru sofnaðir í túnunum.", source: "Halldór Kiljan Laxness" },
  { text: "Vandinn að skrifa er í því fólginn að þegja yfir nógu mörgu.", source: "Halldór Kiljan Laxness" },
  { text: "Ekkert orð er skrípi, ef það stendur á réttum stað.", source: "Halldór Kiljan Laxness" },
  { text: "Sá sem ekki lifir í skáldskap lifir ekki af hér á jörðinni.", source: "Halldór Kiljan Laxness" },
  { text: "Þar sem jökulinn ber við loft hættir landið að vera jarðneskt.", source: "Halldór Kiljan Laxness" },
  { text: "Sá sem kýs ekki réttlæti, hann er ekki maður.", source: "Halldór Kiljan Laxness" },
  { text: "Veröldin er einsog nótt í Róm. Göturnar liggja hver um aðra þvera, hver veit hvert?", source: "Halldór Kiljan Laxness" },
  { text: "Sumir sofa; sumir vaka; sumir eru að fæðast, aðrir að deya.", source: "Halldór Kiljan Laxness" },
  { text: "Fátt er jafnbrigðult og óstöðugt einsog hið elskandi brjóst.", source: "Halldór Kiljan Laxness" },
  { text: "Sannleikurinn kemst ekki uppi moðreyk fyrir vel predikaðri lýgi.", source: "Halldór Kiljan Laxness" },
  { text: "Skáldskapurinn er mál sem lífsandi samtíðarinnar skrifar í mannleg hjörtu.", source: "Halldór Kiljan Laxness" },
  { text: "Var þetta þá kanski lífið: að hafa elskað eitt sumar í æsku, og ekki gert sér það ljóst fyren það var liðið.", source: "Halldór Kiljan Laxness" },
  { text: "Þau töluðu lítið saman og þorðu varla að líta hvort á annað.", source: "Halldór Kiljan Laxness" },
  { text: "Grunntónn tilverunnar er meinlaust grín.", source: "Þórbergur Þórðarson" },
  { text: "Megnið af volæði veraldarinnar stafar af skorti á ímyndunarafli.", source: "Þórbergur Þórðarson" },
  { text: "Rödd hins eilífa verður aldrei endurbætt í hreinskrift.", source: "Þórbergur Þórðarson" },
  { text: "Bækur eru saklausir hlutir, en rithöfundar eru ægilegar verur.", source: "Þórbergur Þórðarson" },
  { text: "Eini auður minn er spekin.", source: "Þórbergur Þórðarson" },
  { text: "Eina stolt mitt er vizkan.", source: "Þórbergur Þórðarson" },
  { text: "Sálir mannanna eru fjötraðar við björg óttans og hleypidómanna.", source: "Þórbergur Þórðarson" },
  { text: "Fólk talar aldrei um það sem er mikið. Það er alltaf að tala um það sem er lítið.", source: "Þórbergur Þórðarson" },
  { text: "Það vilja allir verða ráðherrar, þótt enginn sé fær um að stjórna sjálfum sér.", source: "Þórbergur Þórðarson" },
  { text: "Ástir koma og fara, af því að vér elskum það sem ekki er vert að elska.", source: "Þórbergur Þórðarson" },
  { text: "Sá sem veitir mannkyninu fegurð er mikill velgerðarmaður þess.", source: "Þórbergur Þórðarson" },
  { text: "Sá sem veitir því speki er meiri velgerðarmaður þess.", source: "Þórbergur Þórðarson" },
  { text: "En sá sem veitir því hlátur er mestur velgerðarmaður þess.", source: "Þórbergur Þórðarson" },
  { text: "Þegar mannfólkið er búið að fá afskaplega mikið af framförum þá fer því að leiðast.", source: "Þórbergur Þórðarson" },
  { text: "Þá fer fólkið aftur að tala við veðrið og blómin og steinana.", source: "Þórbergur Þórðarson" },
  { text: "Hjónabandið er samábyrgð tveggja andlegra öreiga.", source: "Þórbergur Þórðarson" },
  { text: "Allir auðmenn eru ræningjar.", source: "Þórbergur Þórðarson" },
  { text: "Hefur nokkurn tíma verið uppi Íslendingur sem er eins eðlilegur í sér og ég.", source: "Þórbergur Þórðarson" },
  { text: "Halldór hefur stíl! Ég hef engan stíl! Halldór er nefnilega virtúós! Ég er séní!", source: "Þórbergur Þórðarson" },
  { text: "Annars er það mín skoðun að músík sé það eina sem er ofaukið í sköpunarverki Drottins.", source: "Þórbergur Þórðarson" },
  { text: "Mér er eintal sálarinnar óþrotlegur auður.", source: "Þórbergur Þórðarson" },
  { text: "Líkami minn er undurfínt hljóðfæri sem englar himinsins og djöflar undirheimsins leika á til skiptis.", source: "Þórbergur Þórðarson" },
  { text: "Það var svo leikandi einfalt að skilja leyndardóma alheimsins meðan hugsunin var óflekkuð af saurgun þekkingarinnar.", source: "Þórbergur Þórðarson" },
  { text: "Og hví skyldu vér amast við bókinni?", source: "Þórbergur Þórðarson" },
  { text: "Að vera fastur fyrir í skoðun var talinn lofsverðari eiginleiki en að leita sannleikans og réttlætisins.", source: "Þórbergur Þórðarson" },
  { text: "En kannski finnst steini ekki lengra að standa í þúsund ár í fjallshlíð en okkur að standa þar í þúsund sekúndur.", source: "Þórbergur Þórðarson" },
  { text: "Ég hlusta í húmi nætur.", source: "Þórbergur Þórðarson" },
  { text: "Ég heyri við yztu höf skóhljóð dáinna daga.", source: "Þórbergur Þórðarson" },
  { text: "Drauma sem huldust gröf.", source: "Þórbergur Þórðarson" },
  { text: "Ísland er svínastía sálarlausra prangara.", source: "Þórbergur Þórðarson" },
  { text: "Þegar stór tíðindi gerast eiga litlir kallar að þegja.", source: "Steinn Steinarr" },
  { text: "Í draumi sérhvers manns er fall hans falið.", source: "Steinn Steinarr" },
  { text: "Kaffihúsin eru minn háskóli.", source: "Steinn Steinarr" },
  { text: "Í minni sveit var svo fallegt útsýni, að við þurftum ekki á skáldskap að halda.", source: "Steinn Steinarr" },
  { text: "Það vinnur aldrei neinn sitt dauðastríð.", source: "Steinn Steinarr" },
  { text: "Skyldi manninum ekki leyðast að láta krossfesta sig?", source: "Steinn Steinarr" },
  { text: "Ég og hamingjan skildum aldrei hvort annað.", source: "Steinn Steinarr" },
  { text: "Það er vandi að umgangast pappír og penna.", source: "Steinn Steinarr" },
  { text: "Tíminn er eins og vatnið.", source: "Steinn Steinarr" },
  { text: "Ég heilsa þér öreigaæska.", source: "Steinn Steinarr" },
  { text: "…ekki er fremur hægt að endurtaka list hins liðna, en jarðarför, sama hve vel hún hefur heppnazt.", source: "Steinn Steinarr" },
  { text: "Þín visna hönd, sem vann þér ei til matar, skal velta þungum steini úr annars braut.", source: "Steinn Steinarr" },
  { text: "Enginn veit um eldinn, sem einu sinni brann.", source: "Steinn Steinarr" },
  { text: "Í landi minna lífsins drauma logaði hann.", source: "Steinn Steinarr" },
  { text: "Víst er þetta löng og erfið leið.", source: "Steinn Steinarr" },
  { text: "En tigið gegnum tál og hverskyns neyð skín takmarkið og bíður eftir þér.", source: "Steinn Steinarr" },
  { text: "Þinn draumur býr þeim mikla mætti yfir að mynda sjálfstætt líf sem ógnar þér.", source: "Steinn Steinarr" },
  { text: "Hann vex á milli þín og þess sem lifir.", source: "Steinn Steinarr" },
  { text: "Að sigra heiminn er eins og að spila á spil með spekingslegum svip og taka í nefið.", source: "Steinn Steinarr" },
  { text: "Og þótt þú tapir, það gerir ekkert til, því það er nefnilega vitlaust gefið.", source: "Steinn Steinarr" },
  { text: "Undan ferðamannsins fæti valt steinn úr stað.", source: "Steinn Steinarr" },
  { text: "Og steinninn hélt áfram að velta, veistu það?", source: "Steinn Steinarr" },
  { text: "Og sjö þúsund árum síðar komst þú, komst þú.", source: "Steinn Steinarr" },
  { text: "Ég hef hlustað svo oft á hin hljóðu tár.", source: "Steinn Steinarr" },
  { text: "Hin hljóðu tár sem í myrkrinu falla.", source: "Steinn Steinarr" },
  { text: "Það er löng leið frá Íslandi til Himnaríkis.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Hart er að verða að híma undir vegg og hafa verið gæðingurinn besti.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Lífið er hverfult, og lánið er valt.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Þú lofaðir mér fögru, en sveikst það allt.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Gler glatast og týnist, gullið í súginn fer.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Stálið er málmurinn mikli, sem meistarinn valdi sér.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Moldin logar af lífi.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Loftið er fullt af söng.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Sumir gera allt í felum.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Ofstjórn er versti vargur allra lýða.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "En illgresi skal eyða með öðrum betri gróðri.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Fáir njóta eldanna, sem fyrstir kveikja þá.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Það hylla fleiri heimskan glóp en hinn, sem lengra sér.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Því gerir meðalmennskan hróp að manni eins og þér.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Í dag skein sól á sundin blá.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Skipið lagði landi frá.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Það syrtir að, er sumir kveðja.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Ég horfi ein á eftir þér.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Hugur minn er hjá þér bundinn.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Löng er nótt við lokuð sundin.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Ég skal biðja og bíða þín.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Uns nóttin dvín og dagur skín.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Til hinsta dags ég hrópa og kalla.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Svo heyrast skal um heima alla.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Frelsið er meira virði en öll auðæfi veraldar.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Enginn maður verður mikill nema hann þori að vera hann sjálfur.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Ástin er sterkust þegar hún krefst einskis.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Sá sem þorir að elska þorir að lifa.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Maðurinn er stærstur þegar hann gleymir sjálfum sér.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Það þarf hugrekki til að vera blíður.", source: "Davíð Stefánsson frá Fagraskógi" },
  { text: "Fegurð hrífur hugann meira ef hjúpuð er, svo andann gruni ennþá fleira en augað sér.", source: "Hannes Hafstein" },
  { text: "Að drepa sjálfan sig er synd gegn lífsins herra. Að lifa sjálfan sig er sjöfalt verra.", source: "Hannes Hafstein" },
  { text: "Lífið er dýrt og dauðinn þess borgun.", source: "Hannes Hafstein" },
  { text: "Þótt allt mig annað bresti, ég eitt á samt: Ég vil.", source: "Hannes Hafstein" },
  { text: "Litla þjóð, með tungum fáum tama.", source: "Hannes Hafstein" },
  { text: "Þegar ég er kominn út fyrir landsteinana, er ég aldrei lengur flokksmaður. Þá er ég aðeins Íslendingur.", source: "Hannes Hafstein" },
  { text: "Og ég mótmæli í nafni konungs og þjóðarinnar þessari aðferð, og ég áskil þinginu rétt til, að klaga til konungs vors yfir lögleysu þeirri, sem hér er höfð í frammi.", source: "Jón Sigurðsson" },
  { text: "Vér mótmælum allir!", source: "Þingmenn á Þjóðfundinum 1851 (að loknum mótmælum Jóns Sigurðssonar)" },
  { text: "Guð blessi Ísland.", source: "Geir H. Haarde" },
  { text: "En Samfylkingin er eins og gamall afturhaldskommatittsflokkur og ætlar sér aldrei að verða stór.", source: "Davíð Oddsson" },
  { text: "Á dögunum var Alþingi sett með guðþjónustu í Dómkirkjunni. Ég tók eftir, að presturinn horfði fyrst á Steingrím, síðan á Ólaf Ragnar, þá á Jón Baldvin og bað svo fyrir þjóðinni.", source: "Davíð Oddsson" },
  { text: "Við verðum að breyta viðhorfi fólks til hins opinbera. Það á ekki að vera eins og síldarnót til að festa fólk í, heldur eins og öryggisnet, sem enginn fellur niður fyrir.", source: "Davíð Oddsson" },
  { text: "Ef þú lítur á mig eins og fasteign þá er ég ekki með neina falda galla.", source: "Davíð Oddsson" },
  { text: "Vinstri flokkarnir eru í nokkrum vanda. Þeim gengur ekki vel, nema þjóðinni gangi illa. Og þjóðinni gengur ekki illa, nema vinstri flokkarnir séu við völd!", source: "Davíð Oddsson" },
  { text: "Vindhanar verða aldrei áttavitar, hvorki til sjós né lands.", source: "Davíð Oddsson" },
  { text: "Þið skuluð ekki kippa ykkur upp við það, hvernig Össur lætur við mig. Hann kemur ekki svona fram við neina aðra en þá, sem eru fyrir framan hann í stafrófinu.", source: "Davíð Oddsson" },
  { text: "Mér finnst það koma úr hörðustu átt, þegar maður talar af lítilsvirðingu um stuttbuxur eftir að hafa haft atvinnu af því að hlaupa um á þeim í áratugi.", source: "Davíð Oddsson (svar við Albert Guðmundsson, 1975)" },
  { text: "Það á ekki að kjósa mig af því að ég er kona, það á að kjósa mig af því að ég er maður.", source: "Vigdís Finnbogadóttir" },
  { text: "Það stóð nú aldrei til að hafa þjóðina á brjósti.", source: "Vigdís Finnbogadóttir" },
  { text: "Orðin eru kastalar okkar Íslendinga. Í fámenni og fátækt týndum við aldrei manndómi okkar. Við gleymdum aldrei að setja í orð — hinn eina varanlega efnivið sem við eigum — allan hag okkar og alla hugsun.", source: "Vigdís Finnbogadóttir (innsetningarræða 1980)" },
  { text: "Allar skoðanir skal endurmeta um leið og ný viðhorf myndast.", source: "Vigdís Finnbogadóttir" },
  { text: "Ég vona að Ísland hafi eitthvað fyrir mig að gera.", source: "Vigdís Finnbogadóttir" },
  { text: "Þó maður sé í Frakklandi þá grætur maður ekki á frönsku. Maður grætur bara á íslensku, ef maður þarf að gráta. Og maður hlær heldur ekki á frönsku, maður hlær á íslensku.", source: "Vigdís Finnbogadóttir" },
  { text: "Ekki má gleyma að ég er alin upp við mikil gildi og heiðarleiki kemur þar fremstur og svo að standa sig. Að standa sig hvað sem á dynur.", source: "Vigdís Finnbogadóttir" },
  { text: "Ég ætla að vona að forseta Íslands verði aldrei neitt það á sem hann getur engum sagt nema maka sínum.", source: "Vigdís Finnbogadóttir" },
  { text: "Mér var ekki afhent keflið í boðhlaupinu, heldur var því hent í mig.", source: "Vigdís Finnbogadóttir" },
  { text: "Ég er með tourette. Ég er með athyglisbrest. Ég get ekki breytt því. Ég er sá sem ég er, þess vegna var ég kosinn borgarstjóri.", source: "Jón Gnarr" },
  { text: "En mistök eru hluti af skapandi hugsunarferli og ef þú ert að reyna að skapa eitthvað nýtt gerir þú fjölda mistaka.", source: "Jón Gnarr" },
  { text: "Að hata er eins og að drekka eitur og bíða svo eftir því að einhver annar drepist.", source: "Jón Gnarr (ræða borgarstjóra um fjárhagsáætlun 2011)" },
  { text: "Að það sé til kærleikur í heiminum er kraftaverk því með réttu ætti harðneskja heimsins fyrir löngu að vera búin að drepa hann.", source: "Jón Gnarr" },
  { text: "People tend to favor the underdog, like in the movies we favor the underdog, but when it comes to voting, we vote for the bully.", source: "Jón Gnarr" },
  { text: "Minn tími mun koma.", source: "Jóhanna Sigurðardóttir" },
  { text: "The secret of getting ahead is getting started.", source: "Mark Twain" },
  { text: "Simplicity is the ultimate sophistication.", source: "Leonardo da Vinci" },
  { text: "What we think, we become.", source: "Buddha" },
  { text: "The only way to do great work is to love what you do.", source: "Steve Jobs" },
  { text: "Whether you think you can or you think you can't, you're right.", source: "Henry Ford" },
  { text: "It always seems impossible until it's done.", source: "Nelson Mandela" },
  { text: "The journey of a thousand miles begins with a single step.", source: "Lao Tzu" },
  { text: "Do not wait to strike till the iron is hot; but make it hot by striking.", source: "William Butler Yeats" },
  { text: "Everything you can imagine is real.", source: "Pablo Picasso" },
  { text: "In the middle of difficulty lies opportunity.", source: "Albert Einstein" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", source: "Eleanor Roosevelt" },
  { text: "Quality is not an act, it is a habit.", source: "Aristotle" },
  { text: "He who has a why to live can bear almost any how.", source: "Friedrich Nietzsche" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", source: "Chinese Proverb" },
  { text: "Act as if what you do makes a difference. It does.", source: "William James" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", source: "Marcus Aurelius" },
  { text: "We suffer more often in imagination than in reality.", source: "Seneca" },
  { text: "It's not what happens to you, but how you react to it that matters.", source: "Epictetus" },
  { text: "The unexamined life is not worth living.", source: "Socrates" },
  { text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", source: "Plato" },
  { text: "Knowing yourself is the beginning of all wisdom.", source: "Aristotle" },
  { text: "It does not matter how slowly you go as long as you do not stop.", source: "Confucius" },
  { text: "A journey of a thousand miles begins with a single step.", source: "Lao Tzu" },
  { text: "Supreme excellence consists of breaking the enemy's resistance without fighting.", source: "Sun Tzu" },
  { text: "Life can only be understood backwards; but it must be lived forwards.", source: "Søren Kierkegaard" },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", source: "Albert Camus" },
  { text: "Freedom is what you do with what's been done to you.", source: "Jean-Paul Sartre" },
  { text: "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.", source: "Bertrand Russell" },
  { text: "The limits of my language mean the limits of my world.", source: "Ludwig Wittgenstein" },
  { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", source: "Carl Jung" },
  { text: "Out of your vulnerabilities will come your strength.", source: "Sigmund Freud" },
  { text: "Between stimulus and response there is a space. In that space is our power to choose our response.", source: "Viktor Frankl" },
  { text: "Imagination is more important than knowledge.", source: "Albert Einstein" },
  { text: "I would rather have questions that can't be answered than answers that can't be questioned.", source: "Richard Feynman" },
  { text: "Somewhere, something incredible is waiting to be known.", source: "Carl Sagan" },
  { text: "Intelligence is the ability to adapt to change.", source: "Stephen Hawking" },
  { text: "Nothing in life is to be feared, it is only to be understood.", source: "Marie Curie" },
  { text: "The present is theirs; the future, for which I really worked, is mine.", source: "Nikola Tesla" },
  { text: "It is not the strongest of the species that survives, but the one most responsive to change.", source: "Charles Darwin" },
  { text: "If I have seen further it is by standing on the shoulders of giants.", source: "Isaac Newton" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", source: "Mark Twain" },
  { text: "Be yourself; everyone else is already taken.", source: "Oscar Wilde" },
  { text: "The world breaks everyone, and afterward, many are strong at the broken places.", source: "Ernest Hemingway" },
  { text: "We are what we pretend to be, so we must be careful about what we pretend to be.", source: "Kurt Vonnegut" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", source: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", source: "Henry David Thoreau" },
  { text: "People will forget what you said, people will forget what you did, but people will never forget how you made them feel.", source: "Maya Angelou" },
  { text: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", source: "Toni Morrison" },
  { text: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", source: "James Baldwin" },
  { text: "No need to hurry. No need to sparkle. No need to be anybody but oneself.", source: "Virginia Woolf" },
  { text: "Everyone thinks of changing the world, but no one thinks of changing himself.", source: "Leo Tolstoy" },
  { text: "The mystery of human existence lies not in just staying alive, but in finding something to live for.", source: "Fyodor Dostoevsky" },
  { text: "Knowledge is of no value unless you put it into practice.", source: "Anton Chekhov" },
  { text: "Anyone who keeps the ability to see beauty never grows old.", source: "Franz Kafka" },
  { text: "I have always imagined that paradise will be a kind of library.", source: "Jorge Luis Borges" },
  { text: "There is always something left to love.", source: "Gabriel García Márquez" },
  { text: "A classic is a book that has never finished saying what it has to say.", source: "Italo Calvino" },
  { text: "You can't go back and change the beginning, but you can start where you are and change the ending.", source: "C.S. Lewis" },
  { text: "Not all those who wander are lost.", source: "J.R.R. Tolkien" },
  { text: "In a time of deceit telling the truth is a revolutionary act.", source: "George Orwell" },
  { text: "There are only two ways to live your life: as though nothing is a miracle, or as though everything is.", source: "Aldous Huxley" },
  { text: "You don't have to burn books to destroy a culture. Just get people to stop reading them.", source: "Ray Bradbury" },
  { text: "It is good to have an end to journey toward; but it is the journey that matters, in the end.", source: "Ursula K. Le Guin" },
  { text: "Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in.", source: "Isaac Asimov" },
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", source: "Arthur C. Clarke" },
  { text: "Fear is the mind-killer.", source: "Frank Herbert" },
  { text: "I may not have gone where I intended to go, but I think I have ended up where I needed to be.", source: "Douglas Adams" },
  { text: "It's not worth doing something unless you were doing something that someone, somewhere, would much rather you weren't doing.", source: "Terry Pratchett" },
  { text: "Books make great gifts because they have whole worlds inside of them.", source: "Neil Gaiman" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", source: "Winston Churchill" },
  { text: "Whatever you are, be a good one.", source: "Abraham Lincoln" },
  { text: "Do what you can, with what you have, where you are.", source: "Theodore Roosevelt" },
  { text: "Be the change that you wish to see in the world.", source: "Mahatma Gandhi" },
  { text: "Darkness cannot drive out darkness; only light can do that.", source: "Martin Luther King Jr." },
  { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", source: "Malcolm X" },
  { text: "If there is no struggle, there is no progress.", source: "Frederick Douglass" },
  { text: "You must never be fearful about what you are doing when it is right.", source: "Rosa Parks" },
  { text: "Happiness is not something ready made. It comes from your own actions.", source: "Dalai Lama" },
  { text: "The most precious gift we can offer others is our presence.", source: "Thich Nhat Hanh" },
  { text: "The wound is the place where the Light enters you.", source: "Rumi" },
  { text: "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.", source: "Khalil Gibran" },
  { text: "You can cut all the flowers but you cannot keep spring from coming.", source: "Pablo Neruda" },
  { text: "Let everything happen to you: beauty and terror. Just keep going. No feeling is final.", source: "Rainer Maria Rilke" },
  { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", source: "Walt Whitman" },
  { text: "Hope is the thing with feathers that perches in the soul.", source: "Emily Dickinson" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", source: "Robert Frost" },
  { text: "Only those who will risk going too far can possibly find out how far one can go.", source: "T.S. Eliot" },
  { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", source: "W.B. Yeats" },
  { text: "Your time is limited, so don't waste it living someone else's life.", source: "Steve Jobs" },
  { text: "Success is a lousy teacher. It seduces smart people into thinking they can't lose.", source: "Bill Gates" },
  { text: "It is far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", source: "Warren Buffett" },
  { text: "The big money is not in the buying and selling, but in the waiting.", source: "Charlie Munger" },
  { text: "The best way to predict the future is to create it.", source: "Peter Drucker" },
  { text: "Whether you think you can, or you think you can't — you're right.", source: "Henry Ford" },
  { text: "If you can dream it, you can do it.", source: "Walt Disney" },
  { text: "The most courageous act is still to think for yourself. Aloud.", source: "Coco Chanel" },
  { text: "Life is either a daring adventure or nothing at all.", source: "Helen Keller" },
  { text: "Whoever is happy will make others happy too.", source: "Anne Frank" },
  { text: "I thought I could organize freedom — how Scandinavian of me.", source: "Björk" },
  { text: "Learning never exhausts the mind.", source: "Leonardo da Vinci" },
  { text: "The greater danger for most of us lies not in setting our aim too high and falling short; but in setting our aim too low, and achieving our mark.", source: "Michelangelo" },
  { text: "I dream my painting and I paint my dream.", source: "Vincent van Gogh" },
  { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", source: "Pablo Picasso" },
  { text: "I am my own muse. I am the subject I know best. The subject I want to know better.", source: "Frida Kahlo" },
  { text: "Don't fear failure. Not failure, but low aim, is the crime. In great attempts it is glorious even to fail.", source: "Bruce Lee" },
  { text: "Don't count the days, make the days count.", source: "Muhammad Ali" },
  { text: "When you come to a fork in the road, take it.", source: "Yogi Berra" },
  { text: "I refuse to join any club that would have me as a member.", source: "Groucho Marx" },
  { text: "What matters most is how well you walk through the fire.", source: "Charles Bukowski" },
  { text: "The man who moves a mountain begins by carrying away small stones.", source: "Confucius" },
  { text: "What we do repeatedly is not an act, but a habit.", source: "Aristotle" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", source: "Marcus Aurelius" },
  { text: "A person often meets his destiny on the road he took to avoid it.", source: "Jean de La Fontaine" },
  { text: "You become what you give your attention to.", source: "Epictetus" },
  { text: "The first principle is that you must not fool yourself—and you are the easiest person to fool.", source: "Richard Feynman" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", source: "Epictetus" },
  { text: "It is not that we have a short time to live, but that we waste much of it.", source: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", source: "Seneca" },
  { text: "The price of anything is the amount of life you exchange for it.", source: "Henry David Thoreau" },
  { text: "Nature does not hurry, yet everything is accomplished.", source: "Lao Tzu" },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", source: "Lao Tzu" },
  { text: "To be everywhere is to be nowhere.", source: "Seneca" },
  { text: "Waste no more time arguing what a good man should be. Be one.", source: "Marcus Aurelius" },
  { text: "The best revenge is not to be like your enemy.", source: "Marcus Aurelius" },
  { text: "An investment in knowledge pays the best interest.", source: "Benjamin Franklin" },
  { text: "Well done is better than well said.", source: "Benjamin Franklin" },
  { text: "Discipline equals freedom.", source: "Jocko Willink" },
  { text: "The more you sweat in peace, the less you bleed in war.", source: "Norman Schwarzkopf" },
  { text: "A ship in harbor is safe, but that is not what ships are built for.", source: "John A. Shedd" },
  { text: "The master has failed more times than the beginner has even tried.", source: "Stephen McCranie" },
  { text: "Try not to become a man of success, but rather a man of value.", source: "Albert Einstein" },
  { text: "The future belongs to those who learn more skills and combine them in creative ways.", source: "Robert Greene" },
  { text: "When performance is measured, performance improves. When performance is measured and reported, the rate of improvement accelerates.", source: "Karl Pearson" },
  { text: "The amateur has a goal. The professional has a system.", source: "James Clear" },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", source: "James Clear" },
  { text: "Focus is saying no to a hundred good ideas.", source: "Steve Jobs" },
  { text: "Simple can be harder than complex.", source: "Steve Jobs" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", source: "Steve Jobs" },
  { text: "If you are not embarrassed by the first version of your product, you've launched too late.", source: "Reid Hoffman" },
  { text: "The biggest risk is not taking any risk.", source: "Mark Zuckerberg" },
  { text: "Persistence is very important. You should not give up unless you are forced to give up.", source: "Elon Musk" },
  { text: "People overestimate what they can do in one year and underestimate what they can do in ten.", source: "Bill Gates" },
  { text: "The most dangerous phrase in the language is: we've always done it this way.", source: "Grace Hopper" },
  { text: "The best way to predict the future is to invent it.", source: "Alan Kay" },
  { text: "If you can't explain it simply, you don't understand it well enough.", source: "Albert Einstein" },
  { text: "The map is not the territory.", source: "Alfred Korzybski" },
  { text: "Reality is that which, when you stop believing in it, doesn't go away.", source: "Philip K. Dick" },
  { text: "Not everything that counts can be counted, and not everything that can be counted counts.", source: "William Bruce Cameron" },
  { text: "The wise man changes his mind; the fool never will.", source: "Spanish Proverb" },
  { text: "Strong opinions, weakly held.", source: "Paul Saffo" },
  { text: "The ability to learn faster than your competitors may be the only sustainable competitive advantage.", source: "Arie de Geus" },
  { text: "What gets measured gets managed.", source: "Peter Drucker" },
  { text: "Culture eats strategy for breakfast.", source: "Peter Drucker" },
  { text: "Efficiency is doing things right; effectiveness is doing the right things.", source: "Peter Drucker" },
  { text: "The bottleneck is always at the point of least understanding.", source: "Eliyahu Goldratt" },
  { text: "The constraint determines the output of the system.", source: "Eliyahu Goldratt" },
  { text: "Compounding is the eighth wonder of the world.", source: "Often Attributed to Albert Einstein" },
  { text: "The chains of habit are too weak to be felt until they are too strong to be broken.", source: "Samuel Johnson" },
  { text: "Every action you take is a vote for the person you wish to become.", source: "James Clear" },
  { text: "Do not seek praise. Seek criticism.", source: "Paul Graham" },
  { text: "The future is already here—it's just not evenly distributed.", source: "William Gibson" },
  { text: "The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself.", source: "George Bernard Shaw" },
  { text: "Risk comes from not knowing what you're doing.", source: "Warren Buffett" },
  { text: "The difference between successful people and really successful people is that really successful people say no to almost everything.", source: "Warren Buffett" },
  { text: "Price is what you pay. Value is what you get.", source: "Warren Buffett" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", source: "Mark Twain" },
  { text: "Continuous improvement is better than delayed perfection.", source: "Mark Twain" },
  { text: "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", source: "Antoine de Saint-Exupéry" },
  { text: "A good plan violently executed now is better than a perfect plan executed next week.", source: "George S. Patton" },
  { text: "He who learns but does not think is lost. He who thinks but does not learn is in great danger.", source: "Confucius" },
  { text: "To know what you know and what you do not know, that is true knowledge.", source: "Confucius" },
  { text: "No man ever steps in the same river twice.", source: "Heraclitus" },
  { text: "Character is fate.", source: "Heraclitus" },
  { text: "Everything should be made as simple as possible, but not simpler.", source: "Often Attributed to Albert Einstein" },
  { text: "The more I learn, the more I realize how much I don't know.", source: "Socrates" },
  { text: "Beware the barrenness of a busy life.", source: "Socrates" },
  { text: "Do not pray for an easy life; pray for the strength to endure a difficult one.", source: "Bruce Lee" },
  { text: "Absorb what is useful, reject what is useless, add what is specifically your own.", source: "Bruce Lee" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", source: "Johann Wolfgang von Goethe" },
  { text: "Whatever you can do or dream you can, begin it.", source: "Johann Wolfgang von Goethe" },
  { text: "Fortune favors the bold.", source: "Virgil" },
  { text: "The obstacle is the path.", source: "Zen Proverb" },
  { text: "Better to light a candle than curse the darkness.", source: "Chinese Proverb" },
  { text: "The person who says it cannot be done should not interrupt the person doing it.", source: "Chinese Proverb" },
  { text: "Fall seven times, stand up eight.", source: "Japanese Proverb" },
  { text: "Vision without action is a daydream. Action without vision is a nightmare.", source: "Japanese Proverb" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", source: "Chinese Proverb" },
  { text: "One day or day one. You decide.", source: "Paulo Coelho" },
  { text: "Freedom is the only worthy goal in life.", source: "Epictetus" },
  { text: "No great thing is created suddenly.", source: "Epictetus" },
  { text: "The greater the difficulty, the more glory in surmounting it.", source: "Epicurus" },
  { text: "First say to yourself what you would be; then do what you have to do.", source: "Epictetus" },
  { text: "What is necessary is never unwise.", source: "Edmund Burke" },
  { text: "The essence of strategy is choosing what not to do.", source: "Michael Porter" },
  { text: "Competition is for losers.", source: "Peter Thiel" },
  { text: "Zero to one is where value is created.", source: "Peter Thiel" },
  { text: "The most contrarian thing of all is not to oppose the crowd but to think for yourself.", source: "Peter Thiel" },
  { text: "The successful warrior is the average man, with laser-like focus.", source: "Bruce Lee" },
  { text: "A year from now you may wish you had started today.", source: "Karen Lamb" },
  { text: "Small disciplines repeated with consistency every day lead to great achievements.", source: "John C. Maxwell" },
  { text: "Time is the friend of the wonderful company, the enemy of the mediocre.", source: "Warren Buffett" },
  { text: "You can have anything you want, but not everything you want.", source: "David Allen" },
  { text: "Software is eating the world.", source: "Marc Andreessen" },
  { text: "The only thing that prepares you to run a company is running a company.", source: "Ben Horowitz" },
  { text: "Your brand is what other people say about you when you're not in the room.", source: "Jeff Bezos" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", source: "Elon Musk" },
  { text: "Make something people want.", source: "Paul Graham" },
  { text: "It is very difficult to make predictions, particularly about the future.", source: "Sam Altman" },
  { text: "Play long-term games with long-term people.", source: "Naval Ravikant" },
  { text: "Only the paranoid survive.", source: "Andy Grove" },
  { text: "Change before you have to.", source: "Jack Welch" },
  { text: "If you don't cannibalize yourself, someone else will.", source: "Steve Jobs" },
  { text: "Business opportunities are like buses — there's always another one coming.", source: "Richard Branson" },
  { text: "Work like there is someone working twenty-four hours a day to take it all away from you.", source: "Mark Cuban" },
  { text: "If you double the number of experiments you do per year, you're going to double your inventiveness.", source: "Jeff Bezos" },
  { text: "Don't be afraid to assume the worst. It's almost always more honest than the official story.", source: "Reed Hastings" },
  { text: "Done is better than perfect.", source: "Sheryl Sandberg" },
  { text: "Don't worry about failure; you only have to be right once.", source: "Drew Houston" },
  { text: "If you're not failing, you're not pushing your limits, and if you're not pushing your limits, you're not maximizing your potential.", source: "Ray Dalio" },
  { text: "The harder the problem, the bigger the opportunity.", source: "Jensen Huang" },
  { text: "Our success has really been based on partnerships from the very beginning.", source: "Bill Gates" },
  { text: "Hire people who are smarter than you and get out of their way.", source: "Lee Iacocca" },
  { text: "If you can't measure it, you can't improve it.", source: "Peter Drucker" },
  { text: "A goal without a plan is just a wish.", source: "Antoine de Saint-Exupéry" },
  { text: "Whenever you see a successful business, someone once made a courageous decision.", source: "Peter Drucker" },
  { text: "You miss 100% of the shots you don't take.", source: "Wayne Gretzky (via Michael Scott)" },
  { text: "The customer's perception is your reality.", source: "Kate Zabriskie" },
  { text: "If you're offered a seat on a rocket ship, don't ask what seat. Just get on.", source: "Sheryl Sandberg" },
  { text: "Speed is the ultimate weapon in business.", source: "Dave Sutton" },
  { text: "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.", source: "Sun Tzu" },
  { text: "Most overnight successes took a long time.", source: "Steve Jobs" },
  { text: "The way to get started is to quit talking and begin doing.", source: "Walt Disney" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", source: "Thomas Edison" },
  { text: "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough.", source: "Mark Zuckerberg" },
  { text: "Whether you are a janitor or a CEO, you should care about the quality of your work.", source: "Howard Schultz" },
  { text: "The best founders work on things that seem small but compound.", source: "Sam Altman" },
  { text: "Build a great product first. The rest is window dressing.", source: "Stewart Butterfield" },
  { text: "Belong anywhere.", source: "Brian Chesky" },
  { text: "Arm the rebels.", source: "Tobias Lütke" },
  { text: "Companies don't have ideas. People do.", source: "Patrick Collison" },
  { text: "Chase the vision, not the money; the money will end up following you.", source: "Tony Hsieh" },
  { text: "Pain plus reflection equals progress.", source: "Ray Dalio" },
  { text: "The empires of the future are the empires of the mind.", source: "Winston Churchill" },
  { text: "Don't find customers for your products, find products for your customers.", source: "Seth Godin" },
  { text: "If you're not embarrassed by your idea, it's not big enough.", source: "Larry Page" },
  { text: "The riskiest thing is to take no risks.", source: "Mark Zuckerberg" },
  { text: "Innovation distinguishes between a leader and a follower.", source: "Steve Jobs" },
  { text: "We are stubborn on vision. We are flexible on details.", source: "Jeff Bezos" },
  { text: "Premature optimization is the root of all evil.", source: "Donald Knuth" },
  { text: "Talk is cheap. Show me the code.", source: "Linus Torvalds" },
  { text: "Computer science is no more about computers than astronomy is about telescopes.", source: "Edsger Dijkstra" },
  { text: "The most damaging phrase in the language is: 'It's always been done that way.'", source: "Grace Hopper" },
  { text: "It's easier to ask forgiveness than it is to get permission.", source: "Grace Hopper" },
  { text: "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.", source: "Brian Kernighan" },
  { text: "There are only two kinds of languages: the ones people complain about and the ones nobody uses.", source: "Bjarne Stroustrup" },
  { text: "When in doubt, use brute force.", source: "Ken Thompson" },
  { text: "UNIX is simple. It just takes a genius to understand its simplicity.", source: "Dennis Ritchie" },
  { text: "We need diversity of thought in the world to face the new challenges.", source: "Tim Berners-Lee" },
  { text: "The internet is not just one thing; it's a collection of things.", source: "Vint Cerf" },
  { text: "You can't have intelligence without emotion.", source: "Marvin Minsky" },
  { text: "He who refuses to do arithmetic is doomed to talk nonsense.", source: "John McCarthy" },
  { text: "Information is the resolution of uncertainty.", source: "Claude Shannon" },
  { text: "That brain of mine is something more than merely mortal, as time will show.", source: "Ada Lovelace" },
  { text: "Never trust a computer you can't throw out a window.", source: "Steve Wozniak" },
  { text: "Free software is a matter of liberty, not price.", source: "Richard Stallman" },
  { text: "Given enough eyeballs, all bugs are shallow.", source: "Eric S. Raymond" },
  { text: "Focused, hard work is the real key to success.", source: "John Carmack" },
  { text: "Sometimes it is the people no one imagines anything of who do the things that no one can imagine.", source: "Alan Turing" },
  { text: "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.", source: "John von Neumann" },
  { text: "The digital revolution is far more significant than the invention of writing or even printing.", source: "Douglas Engelbart" },
  { text: "There was no choice but to be a pioneer.", source: "Margaret Hamilton" },
  { text: "The brains of people are more interesting than the looks I think.", source: "Hedy Lamarr" },
  { text: "Programs should be written for people to read, and only incidentally for machines to execute.", source: "Harold Abelson" },
  { text: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", source: "Bill Gates" },
  { text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", source: "Martin Fowler" },
  { text: "Walking on water and developing software from a specification are easy if both are frozen.", source: "Edward V. Berard" },
  { text: "First, solve the problem. Then, write the code.", source: "John Johnson" },
  { text: "Simplicity is prerequisite for reliability.", source: "Edsger Dijkstra" },
  { text: "Make it work, make it right, make it fast.", source: "Kent Beck" },
  { text: "The function of good software is to make the complex appear to be simple.", source: "Grady Booch" },
  { text: "Software is a great combination of artistry and engineering.", source: "Bill Gates" },
  { text: "Controlling complexity is the essence of computer programming.", source: "Brian Kernighan" },
  { text: "It's not a bug — it's an undocumented feature.", source: "Anonymous" },
  { text: "I'm not a great programmer; I'm just a good programmer with great habits.", source: "Kent Beck" },
  { text: "By the time you've designed a language well enough that everyone wants to use it, it's too late to change it.", source: "Guido van Rossum" },
  { text: "The most disastrous thing that you can ever learn is your first programming language.", source: "Alan Kay" },
  { text: "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies; the other is to make it so complicated that there are no obvious deficiencies.", source: "C.A.R. Hoare" },
  { text: "AI is the new electricity.", source: "Andrew Ng" },
  { text: "We are drowning in information but starved for knowledge.", source: "John Naisbitt" },
  { text: "The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.", source: "Edsger Dijkstra" },
  { text: "Computers are useless. They can only give you answers.", source: "Pablo Picasso" },
  { text: "Code is like humor. When you have to explain it, it's bad.", source: "Cory House" },
  { text: "If debugging is the process of removing software bugs, then programming must be the process of putting them in.", source: "Edsger Dijkstra" },
  { text: "The Net interprets censorship as damage and routes around it.", source: "John Gilmore" },
  { text: "Privacy is not something that I'm merely entitled to, it's an absolute prerequisite.", source: "Marlon Brando" },
  { text: "The most powerful person in the world is the storyteller. The storyteller sets the vision, values, and agenda of an entire generation that is to come.", source: "Steve Jobs" },
  { text: "Computers are good at following instructions, but not at reading your mind.", source: "Donald Knuth" },
  { text: "In the long run we are all dead.", source: "John Maynard Keynes" },
  { text: "There's no such thing as a free lunch.", source: "Milton Friedman" },
  { text: "It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest.", source: "Adam Smith" },
  { text: "The curious task of economics is to demonstrate to men how little they really know about what they imagine they can design.", source: "Friedrich Hayek" },
  { text: "The history of all hitherto existing society is the history of class struggles.", source: "Karl Marx" },
  { text: "Creative destruction is the essential fact about capitalism.", source: "Joseph Schumpeter" },
  { text: "Under capitalism, man exploits man. Under communism, it's just the opposite.", source: "John Kenneth Galbraith" },
  { text: "It is hard to imagine a more stupid or more dangerous way of making decisions than by putting those decisions in the hands of people who pay no price for being wrong.", source: "Thomas Sowell" },
  { text: "Economics is haunted by more fallacies than any other study known to man.", source: "Henry Hazlitt" },
  { text: "Nothing in life is as important as you think it is, while you are thinking about it.", source: "Daniel Kahneman" },
  { text: "Development is not just about increasing wealth but about expanding freedom.", source: "Amartya Sen" },
  { text: "Inequality is not natural — it's the result of choices we make.", source: "Thomas Piketty" },
  { text: "If you see fraud and do not say fraud, you are a fraud.", source: "Nassim Taleb" },
  { text: "The most important thing is to think about what could go wrong.", source: "Howard Marks" },
  { text: "Markets can remain irrational longer than you can remain solvent.", source: "John Maynard Keynes" },
  { text: "In the short run, the market is a voting machine, but in the long run, it is a weighing machine.", source: "Benjamin Graham" },
  { text: "Time in the market beats timing the market.", source: "John Bogle" },
  { text: "Know what you own, and know why you own it.", source: "Peter Lynch" },
  { text: "Comparative advantage is the most powerful idea in economics.", source: "David Ricardo" },
  { text: "The state is the great fiction by which everybody seeks to live at the expense of everybody else.", source: "Frédéric Bastiat" },
  { text: "When the legal mechanism allows the looters to gain at the expense of the looted, then everyone becomes a looter or a victim.", source: "Murray Rothbard" },
  { text: "Government is the only institution that can take a valuable commodity like paper and make it worthless by applying ink.", source: "Ludwig von Mises" },
  { text: "Free markets do not necessarily lead to efficient outcomes.", source: "Joseph Stiglitz" },
  { text: "The only function of economic forecasting is to make astrology look respectable.", source: "John Kenneth Galbraith" },
  { text: "Stability is destabilizing.", source: "Hyman Minsky" },
  { text: "The first principle of economics is that every agent is actuated only by self-interest.", source: "Francis Edgeworth" },
  { text: "Capitalism is the astounding belief that the most wickedest of men will do the most wickedest of things for the greatest good of everyone.", source: "John Maynard Keynes" },
  { text: "An economist is an expert who will know tomorrow why the things he predicted yesterday didn't happen today.", source: "Laurence J. Peter" },
  { text: "Inflation is taxation without legislation.", source: "Milton Friedman" },
  { text: "Be fearful when others are greedy and greedy when others are fearful.", source: "Warren Buffett" },
  { text: "Diversification is protection against ignorance.", source: "Warren Buffett" },
  { text: "The four most dangerous words in investing are: 'this time it's different.'", source: "Sir John Templeton" },
  { text: "The stock market is filled with individuals who know the price of everything, but the value of nothing.", source: "Philip Fisher" },
  { text: "Wide diversification is only required when investors do not understand what they are doing.", source: "Warren Buffett" },
  { text: "Bull markets are born on pessimism, grow on skepticism, mature on optimism, and die on euphoria.", source: "Sir John Templeton" },
  { text: "Money is a tool. It can be used for good or evil.", source: "Ayn Rand" },
  { text: "Compound interest is the eighth wonder of the world. He who understands it, earns it; he who doesn't, pays it.", source: "Attributed to Albert Einstein" },
  { text: "The function of economic forecasting is to make astrology look respectable.", source: "Ezra Solomon" },
  { text: "Without deviation from the norm, progress is not possible.", source: "Frank Zappa" },
  { text: "He not busy being born is busy dying.", source: "Bob Dylan" },
  { text: "Life is what happens to you while you're busy making other plans.", source: "John Lennon" },
  { text: "I don't know where I'm going from here, but I promise it won't be boring.", source: "David Bowie" },
  { text: "Don't play what's there, play what's not there.", source: "Miles Davis" },
  { text: "If you have to ask what jazz is, you'll never know.", source: "Louis Armstrong" },
  { text: "There are two kinds of music — good music, and the other kind.", source: "Duke Ellington" },
  { text: "Knowledge speaks, but wisdom listens.", source: "Jimi Hendrix" },
  { text: "I won't be a rock star. I will be a legend.", source: "Freddie Mercury" },
  { text: "A strong spirit transcends rules.", source: "Prince" },
  { text: "Be a first rate version of yourself, not a second rate version of someone else.", source: "Judy Garland" },
  { text: "I'm not a businessman — I'm a business, man.", source: "Jay-Z" },
  { text: "The most valuable thing you can make is a mistake — you can't learn anything from being perfect.", source: "Adam Osborne" },
  { text: "I like beautiful melodies telling me terrible things.", source: "Tom Waits" },
  { text: "There is a crack in everything — that's how the light gets in.", source: "Leonard Cohen" },
  { text: "I'm forever chasing after time, but it disappears so fast.", source: "Nick Cave" },
  { text: "In art and dream may you proceed with abandon.", source: "Patti Smith" },
  { text: "I could drink a case of you and still be on my feet.", source: "Joni Mitchell" },
  { text: "It's better to burn out than to fade away.", source: "Neil Young" },
  { text: "It's the singer, not the song.", source: "Mick Jagger" },
  { text: "Some things you have to do every day. Eating seven apples on Saturday night instead of one a day just isn't going to get the job done.", source: "Jim Rohn" },
  { text: "If you don't know the blues, there's no point in picking up the guitar.", source: "Keith Richards" },
];
